spring:
  datasource:
    url: jdbc:mysql://localhost:3306/juxta_database
    # url: jdbc:mysql://myapp-mysql:3306/docker_db_test?autoReconnect=true&useSSL=false
    # use sll = false for <= v5.7
    username: user
    password: test
  jpa:
    hibernate-ddl.auto: update
    generate-ddl: true
    show-sql: true
logging:
  level:
    com.example: TRACE