version: '3'

services:
  mysql-db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=docker_db_test
      - MYSQL_USER=user
      - MYSQL_PASSWORD=test
    ports:
      - 3307:3306
    volumes:
      - mysql-volume:/var/lib/mysql
  server:
    build:
      context: ./../../
      dockerfile: ./docker/release/app/Dockerfile
    restart: on-failure
    depends_on:
      - mysql-db
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=mysql-db
      - DATABASE_USER=user
      - DATABASE_PASSWORD=test
      - DATABASE_NAME=docker_db_test
      - DATABASE_PORT=3306
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/docker_db_test?autoReconnect=true&useSSL=false
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
volumes:
  mysql-volume:
